Repository huggingface/accelerate, pull requests merged in 2023-05, with the labels that each got.

#962 Log Images and other types to wandb
  src/accelerate/tracking.py
Labels: enhancement, wip

#1391 Fix gather_obj
  src/accelerate/test_utils/scripts/test_ops.py
  src/accelerate/utils/operations.py
  tests/test_multigpu.py
Labels: bug

#1410 Distributed prompting/inference utility
  docs/source/_toctree.yml
  docs/source/usage_guides/distributed_inference.mdx
  src/accelerate/accelerator.py
  src/accelerate/state.py
  src/accelerate/test_utils/scripts/test_script.py
Labels: enhancement

#1452 Auto multigpu logic
  src/accelerate/commands/launch.py
Labels: enhancement

#1453 Update with cli instructions
  docs/source/basic_tutorials/launch.mdx
  docs/source/usage_guides/distributed_inference.mdx
Labels: documentation

#1457 Document how to use commands with python module instead of argparse
  docs/source/basic_tutorials/launch.mdx
  docs/source/package_reference/cli.mdx
Labels: documentation

#1466 Fix skip first batch being perminant
  docs/source/usage_guides/checkpoint.mdx
  examples/by_feature/checkpointing.py
  examples/complete_cv_example.py
  examples/complete_nlp_example.py
  src/accelerate/accelerator.py
  tests/test_examples.py
Labels: bug

#1477 Split tensors as part of `split_between_processes`
  src/accelerate/accelerator.py
  src/accelerate/state.py
  src/accelerate/test_utils/scripts/test_script.py
Labels: enhancement

#1490 Add rdzv-backend
  docs/source/package_reference/cli.mdx
  src/accelerate/commands/launch.py
Labels: enhancement

#1495 Only use IPEX if available
  src/accelerate/accelerator.py
Labels: bug
